build.gradle
src/main/java/com/back/catchmate/domain/board/entity/Board.java
src/main/java/com/back/catchmate/domain/enroll/entity/AcceptStatus.java
src/main/java/com/back/catchmate/domain/enroll/entity/Enroll.java
src/main/java/com/back/catchmate/domain/notification/entity/Notification.java
src/main/java/com/back/catchmate/domain/user/entity/AlarmType.java
src/main/java/com/back/catchmate/domain/user/entity/Provider.java
src/main/java/com/back/catchmate/domain/user/entity/User.java
src/main/java/com/back/catchmate/global/entity/BaseTimeEntity.java

feat : 데이터베이스 세팅 및 엔티티 설계

---

src/main/java/com/back/catchmate/domain/user/service/UserServiceImpl.java
src/main/java/com/back/catchmate/global/s3/S3Service.java

[FIX] S3 오류 해결

---

src/main/java/com/back/catchmate/domain/club/controller/ClubController.java
src/main/java/com/back/catchmate/domain/club/converter/ClubConverter.java
src/main/java/com/back/catchmate/domain/club/dto/ClubResponse.java
src/main/java/com/back/catchmate/domain/club/service/ClubService.java
src/main/java/com/back/catchmate/domain/club/service/ClubServiceImpl.java
src/main/java/com/back/catchmate/global/config/SecurityConfig.java

[FEAT] 구단 목록 조회 기능 구현

---

src/main/java/com/back/catchmate/global/config/AsyncConfig.java
src/main/java/com/back/catchmate/global/config/FCMConfig.java

[FEAT] 설정 파일 추가

---

src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
src/main/java/com/back/catchmate/domain/board/entity/Board.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/board/service/BoardService.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/global/entity/BaseTimeEntity.java

feat : 게시글 삭제 API 기능 구현

---

src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
src/main/java/com/back/catchmate/domain/board/entity/Board.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/board/service/BoardService.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
src/main/java/com/back/catchmate/domain/enroll/entity/Enroll.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/game/dto/GameResponse.java
src/main/java/com/back/catchmate/domain/game/entity/Game.java
src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java
src/main/java/com/back/catchmate/domain/notification/dto/NotificationResponse.java
src/main/java/com/back/catchmate/global/entity/BaseTimeEntity.java

[FEAT] 게시글 단일 조회 기능 구현

---

build.gradle
src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryCustom.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
src/main/java/com/back/catchmate/domain/board/service/BoardService.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/global/config/QueryDslConfig.java

[FEAT] 게시글 전체 조회시 필터 기능 구현

---

src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/board/service/BoardService.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java

[FEAT] 상대방이 작성한 게시글 조회 기능 구현

---

src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
src/main/java/com/back/catchmate/domain/board/entity/Board.java
src/main/java/com/back/catchmate/domain/board/service/BoardService.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/game/entity/Game.java
src/main/java/com/back/catchmate/domain/user/entity/User.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

[FEAT] 게시글 수정 API 기능 구현

---

src/main/java/com/back/catchmate/domain/game/converter/GameConverter.java

fix : build 오류 수정

---

src/main/java/com/back/catchmate/domain/board/entity/BookMark.java

[FIX] 테이블명 수정

---

src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

[FIX] 게시글 임시 저장 로직 수정

---

src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryCustom.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
src/main/java/com/back/catchmate/domain/board/service/BoardService.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java
src/main/java/com/back/catchmate/domain/notification/dto/NotificationResponse.java
src/main/java/com/back/catchmate/domain/notification/entity/Notification.java
src/main/java/com/back/catchmate/domain/notification/service/NotificationService.java
src/main/java/com/back/catchmate/domain/notification/service/NotificationServiceImpl.java

[FIX] API 수정

---

src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java

[FIX] 임시저장 로직 수정

---

src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
src/main/java/com/back/catchmate/domain/board/service/BoardService.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java

[FIX] 게시글 상세 조회시 찜 여부 컬럼 추가

---

src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java

[FIX] 알림 응답값 수정

---

src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java

[FIX] 게시글 응답값에 게시글 버튼 상태 컬럼 추가

---

src/main/java/com/back/catchmate/domain/board/entity/Board.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java

#68 
임시 저장 게시글이 있을 경우에 게시글을 작성했을 경우, 해당 임시 저장 게시글 삭제 로직 추가

[FIX] 임시 저장 게시글이 있을 경우에 게시글을 작성했을 경우, 해당 임시 저장 게시글 삭제 로직 추가

---

src/main/java/com/back/catchmate/domain/notification/dto/FCMMessageRequest.java
src/main/java/com/back/catchmate/domain/notification/service/FCMService.java

[FIX] PUSH 알림 메세지 수정

---

src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
src/main/java/com/back/catchmate/domain/board/entity/Board.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/entity/UserChatRoom.java
src/main/java/com/back/catchmate/domain/chat/repository/ChatRoomRepository.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

#58 
채팅방 생성 기능 구현 및 직관 신청 수락시 채팅방 입장 기능 구현

[FEAT] 채팅방 생성 기능 구현 및 직관 신청 수락시 채팅방 입장 기능 구현

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
src/main/java/com/back/catchmate/domain/chat/converter/ChatRoomConverter.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
src/main/java/com/back/catchmate/domain/chat/repository/UserChatRoomRepository.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java

#58 
- 내가 속한 채팅방 리스트 구현
- 채팅방 입장시 채팅방 인원 추가 기능 구현

[FEAT] 내가 속한 채팅방 리스트 구현

---

src/main/java/com/back/catchmate/domain/board/entity/Board.java
src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomService.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

#58 
채팅 메세지 & 채팅방 리스트 조회 요청 주소 변경

[FEAT] 채팅 메세지 & 채팅방 리스트 조회 요청 주소 변경

---

src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java

[FIX] 게시글 버튼 상태 확인 로직 수정

---

src/main/java/com/back/catchmate/domain/chat/dto/ChatRequest.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
src/main/java/com/back/catchmate/domain/chat/entity/ChatMessage.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

[FIX] 채팅 전송시에 요청하는 필드값 수정

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
src/main/java/com/back/catchmate/domain/chat/converter/ChatMessageConverter.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
src/main/java/com/back/catchmate/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/back/catchmate/domain/chat/repository/ChatRoomRepository.java
src/main/java/com/back/catchmate/domain/chat/repository/UserChatRoomRepository.java
src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

[FEAT] 채팅 내역 조회 기능 구현

---

src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/service/FCMService.java
src/main/java/com/back/catchmate/domain/topic/controller/TopicController.java
src/main/java/com/back/catchmate/domain/topic/dto/TopicRequest.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

[FEAT] 채팅 알림 전송 기능 구현

---

src/main/java/com/back/catchmate/domain/chat/converter/ChatMessageConverter.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
src/main/java/com/back/catchmate/domain/chat/service/ChatService.java

[FIX] 채팅 메세지 반환값 추가

---

src/main/java/com/back/catchmate/domain/inquiry/controller/InquiryController.java
src/main/java/com/back/catchmate/domain/inquiry/converter/InquiryConverter.java
src/main/java/com/back/catchmate/domain/inquiry/dto/InquiryRequest.java
src/main/java/com/back/catchmate/domain/inquiry/entity/Inquiry.java
src/main/java/com/back/catchmate/domain/inquiry/entity/InquiryType.java
src/main/java/com/back/catchmate/domain/inquiry/repository/InquiryRepository.java
src/main/java/com/back/catchmate/domain/inquiry/service/InquiryService.java
src/main/java/com/back/catchmate/domain/inquiry/service/InquiryServiceImpl.java
src/main/java/com/back/catchmate/domain/report/controller/ReportController.java
src/main/java/com/back/catchmate/domain/report/converter/ReportConverter.java
src/main/java/com/back/catchmate/domain/report/dto/ReportRequest.java
src/main/java/com/back/catchmate/domain/report/entity/ReportType.java
src/main/java/com/back/catchmate/domain/report/service/ReportServiceImpl.java

[FEAT] 고객센터 문의 API 구현

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java
src/main/java/com/back/catchmate/domain/chat/repository/UserChatRoomRepository.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/UserChatRoomService.java
src/main/java/com/back/catchmate/domain/chat/service/UserChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/service/FCMService.java

[FIX] 채팅방에 속한 인원 조회 API 수정

---

src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryCustom.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java
src/main/java/com/back/catchmate/domain/chat/entity/UserChatRoom.java
src/main/java/com/back/catchmate/domain/chat/service/UserChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/user/controller/UserController.java
src/main/java/com/back/catchmate/domain/user/converter/BlockerUserConverter.java
src/main/java/com/back/catchmate/domain/user/converter/UserConverter.java
src/main/java/com/back/catchmate/domain/user/dto/UserResponse.java
src/main/java/com/back/catchmate/domain/user/entity/BlockedUser.java
src/main/java/com/back/catchmate/domain/user/repository/BlockedUserRepository.java
src/main/java/com/back/catchmate/domain/user/service/BlockedUserService.java
src/main/java/com/back/catchmate/domain/user/service/BlockedUserServiceImpl.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

[FEAT] 유저 차단 API 기능 구현

---

src/main/java/com/back/catchmate/domain/admin/controller/AdminController.java
src/main/java/com/back/catchmate/domain/admin/converter/AdminConverter.java
src/main/java/com/back/catchmate/domain/admin/dto/AdminResponse.java
src/main/java/com/back/catchmate/domain/admin/service/AdminService.java
src/main/java/com/back/catchmate/domain/admin/service/AdminServiceImpl.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/inquiry/repository/InquiryRepository.java
src/main/java/com/back/catchmate/domain/report/repository/ReportRepository.java
src/main/java/com/back/catchmate/domain/user/converter/UserConverter.java
src/main/java/com/back/catchmate/domain/user/dto/UserResponse.java
src/main/java/com/back/catchmate/domain/user/entity/Authority.java
src/main/java/com/back/catchmate/domain/user/entity/User.java
src/main/java/com/back/catchmate/domain/user/repository/UserRepository.java
src/main/java/com/back/catchmate/global/config/SecurityConfig.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java
src/main/java/com/back/catchmate/global/jwt/JwtAuthenticationFilter.java

[FEAT] 관리자 메인 페이지 API 구현

---

src/main/java/com/back/catchmate/domain/admin/controller/AdminController.java

[DOCS] swagger 문서화

---

src/main/java/com/back/catchmate/domain/admin/controller/AdminController.java
src/main/java/com/back/catchmate/domain/admin/converter/AdminConverter.java
src/main/java/com/back/catchmate/domain/admin/dto/AdminResponse.java
src/main/java/com/back/catchmate/domain/admin/service/AdminService.java
src/main/java/com/back/catchmate/domain/admin/service/AdminServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/entity/ChatRoom.java
src/main/java/com/back/catchmate/domain/user/repository/UserRepository.java

[FEAT] 게시글 모니터링 관련 API 구현

---

src/main/java/com/back/catchmate/domain/board/entity/Board.java
src/main/java/com/back/catchmate/domain/chat/entity/ChatRoom.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
src/main/java/com/back/catchmate/global/config/MongodbConfig.java

[FIX] API 오류 수정

---

src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/chat/repository/ChatRoomRepository.java
src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/user/entity/BlockedUser.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

[FIX] 직관 신청시 발생하는 동시성 이슈 해결

---

src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/user/repository/BlockedUserRepository.java

Closes 
사용자를 차단 해제했을 때, 게시글이 보이지않는 오류 수정

[FIX] 사용자를 차단 해제했을 때, 게시글이 보이지않는 오류 수정

---

src/main/java/com/back/catchmate/domain/admin/converter/AdminConverter.java
src/main/java/com/back/catchmate/domain/admin/dto/AdminResponse.java
src/main/java/com/back/catchmate/domain/admin/service/AdminServiceImpl.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/user/repository/UserRepository.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

[FIX] 구단별 가입자 수 관리자 API 수정

---

src/main/java/com/back/catchmate/domain/admin/notice/controller/NoticeController.java
src/main/java/com/back/catchmate/domain/admin/notice/converter/NoticeConverter.java
src/main/java/com/back/catchmate/domain/admin/notice/dto/NoticeRequest.java
src/main/java/com/back/catchmate/domain/admin/notice/dto/NoticeResponse.java
src/main/java/com/back/catchmate/domain/admin/notice/entity/Notice.java
src/main/java/com/back/catchmate/domain/admin/notice/repository/NoticeRepository.java
src/main/java/com/back/catchmate/domain/admin/notice/service/NoticeService.java
src/main/java/com/back/catchmate/domain/admin/notice/service/NoticeServiceImpl.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

feat : 공지사항 CRUD API 기능 구현

---

src/main/java/com/back/catchmate/domain/admin/controller/AdminController.java
src/main/java/com/back/catchmate/domain/admin/converter/AdminConverter.java
src/main/java/com/back/catchmate/domain/admin/dto/AdminRequest.java
src/main/java/com/back/catchmate/domain/admin/dto/AdminResponse.java
src/main/java/com/back/catchmate/domain/admin/service/AdminService.java
src/main/java/com/back/catchmate/domain/admin/service/AdminServiceImpl.java
src/main/java/com/back/catchmate/domain/inquiry/controller/InquiryController.java
src/main/java/com/back/catchmate/domain/inquiry/converter/InquiryConverter.java
src/main/java/com/back/catchmate/domain/inquiry/dto/InquiryResponse.java
src/main/java/com/back/catchmate/domain/inquiry/entity/Inquiry.java
src/main/java/com/back/catchmate/domain/inquiry/service/InquiryService.java
src/main/java/com/back/catchmate/domain/inquiry/service/InquiryServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/message/NotificationMessages.java
src/main/java/com/back/catchmate/domain/notification/service/FCMService.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

[FEAT] 문의 내역 관리자 API 구현

---

src/main/java/com/back/catchmate/domain/admin/controller/AdminController.java
src/main/java/com/back/catchmate/domain/admin/converter/AdminConverter.java
src/main/java/com/back/catchmate/domain/admin/dto/AdminResponse.java
src/main/java/com/back/catchmate/domain/admin/notice/controller/NoticeController.java
src/main/java/com/back/catchmate/domain/admin/notice/entity/Notice.java
src/main/java/com/back/catchmate/domain/admin/notice/service/NoticeServiceImpl.java
src/main/java/com/back/catchmate/domain/admin/service/AdminService.java
src/main/java/com/back/catchmate/domain/admin/service/AdminServiceImpl.java
src/main/java/com/back/catchmate/domain/report/entity/Report.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java

[FEAT] 유저 신고 관리자 API 구현

---

src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
src/main/java/com/back/catchmate/domain/report/controller/ReportController.java
src/main/java/com/back/catchmate/domain/report/service/ReportService.java
src/main/java/com/back/catchmate/domain/report/service/ReportServiceImpl.java

Closes 
채팅 오류 해결 및 유저 차단 API 수정

[FIX] 채팅 오류 해결 및 유저 차단 API 수정

---

src/main/java/com/back/catchmate/domain/report/dto/ReportRequest.java

fix : 유저 차단 API 수정

---

src/main/java/com/back/catchmate/domain/admin/notice/controller/NoticeController.java
src/main/java/com/back/catchmate/domain/admin/notice/converter/NoticeConverter.java
src/main/java/com/back/catchmate/domain/admin/notice/dto/NoticeResponse.java
src/main/java/com/back/catchmate/domain/admin/notice/entity/Notice.java
src/main/java/com/back/catchmate/domain/admin/notice/service/NoticeService.java
src/main/java/com/back/catchmate/domain/admin/notice/service/NoticeServiceImpl.java

[FIX] 공지사항 API 수정

---

src/main/java/com/back/catchmate/domain/admin/notice/controller/NoticeController.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/dto/FCMMessageRequest.java
src/main/java/com/back/catchmate/domain/notification/service/FCMService.java

Closes 
직관 신청 수락 PUSH 알림에 데이터 추가

[FIX] 직관 신청 수락 PUSH 알림에 데이터 추가

---

src/main/java/com/back/catchmate/domain/admin/controller/AdminController.java
src/main/java/com/back/catchmate/domain/admin/service/AdminServiceImpl.java
src/main/java/com/back/catchmate/domain/inquiry/entity/Inquiry.java
src/main/java/com/back/catchmate/domain/inquiry/repository/InquiryRepository.java
src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java
src/main/java/com/back/catchmate/domain/notification/entity/Notification.java
src/main/java/com/back/catchmate/domain/notification/message/NotificationMessages.java
src/main/java/com/back/catchmate/domain/notification/service/NotificationService.java
src/main/java/com/back/catchmate/domain/notification/service/NotificationServiceImpl.java

[FIX] 문의사항 API 수정

---

src/main/java/com/back/catchmate/domain/chat/converter/ChatRoomConverter.java
src/main/java/com/back/catchmate/domain/chat/converter/UserChatRoomConverter.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
src/main/java/com/back/catchmate/domain/chat/entity/UserChatRoom.java
src/main/java/com/back/catchmate/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomService.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

[FEAT] 읽지 않은 채팅 개수 조회 기능 구현

---

src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/converter/ChatRoomConverter.java
src/main/java/com/back/catchmate/domain/chat/converter/UserChatRoomConverter.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
src/main/java/com/back/catchmate/domain/chat/entity/UserChatRoom.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/service/FCMService.java
src/main/java/com/back/catchmate/global/config/SecurityConfig.java
src/main/java/com/back/catchmate/global/jwt/JwtOptionalValidateArgumentResolver.java
src/main/java/com/back/catchmate/global/jwt/OptionalJwtValidation.java

#151 
비회원 게시글 리스트 조회 기능 구현 및 새로운 채팅방 여부 기능 구현

[FEAT] 비회원 게시글 리스트 조회 기능 구현 및 새로운 채팅방 여부 기능 구현

---

src/main/java/com/back/catchmate/domain/admin/service/AdminServiceImpl.java

[FIX] 관리자 응원 통계 API 오류 수정

---

src/main/java/com/back/catchmate/global/config/WebSocketConfig.java
src/main/java/com/back/catchmate/global/error/ErrorCode.java
src/main/java/com/back/catchmate/global/handler/ChatPreHandler.java

[REFACTOR] 채팅 STOMP 핸들러 추가

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatRequest.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/service/FCMService.java

#157 
채팅 읽지 않은 메세지 개수 조회 기능 실시간으로 수정

[FIX] 채팅 읽지 않은 메세지 개수 조회 기능 수정

---

src/main/java/com/back/catchmate/domain/user/controller/UserController.java
src/main/java/com/back/catchmate/domain/user/entity/User.java
src/main/java/com/back/catchmate/domain/user/repository/UserRepository.java
src/main/java/com/back/catchmate/domain/user/service/UserService.java
src/main/java/com/back/catchmate/domain/user/service/UserServiceImpl.java
src/main/java/com/back/catchmate/global/auth/service/AuthServiceImpl.java

[FEAT] 유저 탈퇴 API 구현

---

src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

[FIX] 채팅 로그 추가

---

src/main/java/com/back/catchmate/domain/chat/entity/UserChatRoom.java

[FIX] DB 저장시 한국 시간으로 저장되도록 수정

---

src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

[FIX] 날짜 비교 로직 수정

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java
src/main/java/com/back/catchmate/domain/chat/entity/UserChatRoom.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomService.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatSessionService.java
src/main/java/com/back/catchmate/global/handler/ChatPreHandler.java

#168 
채팅방 접속 여부 기능 구현 및 채팅방 개별 알림 설정 기능 구현

[FEAT] 채팅방 접속 여부 기능 구현 및 채팅방 개별 알림 설정 기능 구현

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java

[DOCS] Swagger 설정

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java
src/main/java/com/back/catchmate/domain/chat/converter/ChatRoomConverter.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
src/main/java/com/back/catchmate/domain/chat/repository/UserChatRoomRepository.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/UserChatRoomService.java
src/main/java/com/back/catchmate/domain/chat/service/UserChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/repository/NotificationRepository.java
src/main/java/com/back/catchmate/domain/notification/service/NotificationService.java
src/main/java/com/back/catchmate/domain/notification/service/NotificationServiceImpl.java
src/main/java/com/back/catchmate/domain/user/controller/UserController.java
src/main/java/com/back/catchmate/domain/user/converter/UserConverter.java
src/main/java/com/back/catchmate/domain/user/dto/UserResponse.java
src/main/java/com/back/catchmate/domain/user/service/UserService.java
src/main/java/com/back/catchmate/domain/user/service/UserServiceImpl.java

#171 
채팅방 정보 수정 및 읽지 않은 채팅 혹은 알림 여부 기능 구현

[FEAT] 채팅방 정보 수정 및 읽지 않은 채팅 혹은 알림 여부 기능 구현

---

src/main/java/com/back/catchmate/domain/admin/controller/AdminController.java
src/main/java/com/back/catchmate/domain/admin/converter/AdminConverter.java
src/main/java/com/back/catchmate/domain/admin/dto/AdminResponse.java

[FIX] 신고내역 조회 API 수정

---

src/main/java/com/back/catchmate/CatchmateApplication.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/back/catchmate/global/scheduler/BoardCleanScheduler.java

#176 
스케줄러를 사용하여 특정 기간이 지난 게시글 자동 삭제 기능 구현

[FEAT] 스케줄러를 사용하여 특정 기간이 지난 게시글 자동 삭제 기능 구현

---

src/main/java/com/back/catchmate/global/handler/ChatPreHandler.java
src/main/java/com/back/catchmate/global/scheduler/BoardCleanScheduler.java

[FIX] 테스트 로그 추가

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatSessionService.java
src/main/java/com/back/catchmate/global/handler/ChatPreHandler.java

[FIX] 테스트를 위한 로그 출력

---

src/main/java/com/back/catchmate/global/handler/ChatPreHandler.java

[FIX] 테스트를 위한 로그 추가

---

src/main/java/com/back/catchmate/domain/admin/service/AdminServiceImpl.java

[FIX] 문의 답변 알림 데이터 저장되도록 수정

---

src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java

[FIX] 알람 정보 조회 API 수정

---

src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/repository/NotificationRepository.java

[FIX] 직관 신청 알림 API 수정

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatRequest.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

[FIX] 디버깅을 위한 로그 추가

---

src/main/java/com/back/catchmate/domain/chat/service/ChatSessionService.java
src/main/java/com/back/catchmate/global/handler/ChatPreHandler.java

[FIX] 불필요한 로그 삭제

---

src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

Closes 
채팅 마지막 읽은 시간 즉시 반영 되도록 수정

[FIX] 채팅 마지막 읽은 시간 즉시 반영 되도록 수정

---

src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java

Closes 
Transactional 어노테이션 삭제

[FIX] Transactional 어노테이션 삭제

---

src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
src/main/java/com/back/catchmate/domain/chat/converter/ChatMessageConverter.java
src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
src/main/java/com/back/catchmate/domain/chat/repository/ChatMessageRepository.java
src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

#190 
채팅 리스트 id 기반으로 페이징 처리 하도록 수정

[FIX] 채팅 리스트 id 기반으로 페이징 처리 하도록 수정

---

src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java

#192 
소켓 메세지 받을 때, 채팅 id값 받도록 수정

[FIX] 소켓 메세지 받을 때, 채팅 id값 받도록 수정

---

.github/workflows/deploy.yml
src/main/java/com/back/catchmate/global/config/SwaggerConfig.java

[CICD] 운영 서버 배포 서버 분리 테스트

---

src/main/resources/application.yml

[FIX] application.yml 파일 수정

---

src/main/java/com/back/catchmate/domain/admin/controller/AdminController.java
src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java
src/main/java/com/back/catchmate/domain/notification/entity/Notification.java
src/main/java/com/back/catchmate/domain/notification/repository/NotificationRepository.java
src/main/java/com/back/catchmate/domain/notification/service/NotificationService.java
src/main/java/com/back/catchmate/domain/notification/service/NotificationServiceImpl.java
src/main/resources/application.yml

[FIX] 직관신청 취소시, 발생하는 오류 수정

---

src/main/java/com/back/catchmate/domain/user/controller/UserController.java
src/main/java/com/back/catchmate/domain/user/converter/UserConverter.java
src/main/java/com/back/catchmate/domain/user/dto/UserRequest.java
src/main/java/com/back/catchmate/domain/user/dto/UserResponse.java
src/main/java/com/back/catchmate/domain/user/entity/User.java
src/main/java/com/back/catchmate/domain/user/repository/UserRepository.java
src/main/java/com/back/catchmate/domain/user/service/BlockedUserServiceImpl.java
src/main/java/com/back/catchmate/domain/user/service/UserServiceImpl.java
src/main/java/com/back/catchmate/global/auth/converter/AuthConverter.java
src/main/java/com/back/catchmate/global/auth/dto/AuthRequest.java
src/main/java/com/back/catchmate/global/auth/repository/RefreshTokenRepository.java
src/main/java/com/back/catchmate/global/auth/service/AuthServiceImpl.java
src/main/java/com/back/catchmate/global/config/AmazonConfig.java
src/main/java/com/back/catchmate/global/config/SecurityConfig.java
src/main/java/com/back/catchmate/global/config/WebConfig.java
src/main/java/com/back/catchmate/global/handler/ChatPreHandler.java
src/main/java/com/back/catchmate/global/jwt/JwtAuthenticationFilter.java
src/main/java/com/back/catchmate/global/jwt/JwtService.java

[REFACTOR] 사용자 도메인 관련 코드 리팩토링

---

src/main/generated/com/back/catchmate/domain/board/entity/QBoard.java
src/main/generated/com/back/catchmate/domain/board/entity/QBookMark.java
src/main/generated/com/back/catchmate/domain/chat/entity/QChatRoom.java
src/main/generated/com/back/catchmate/domain/chat/entity/QUserChatRoom.java
src/main/generated/com/back/catchmate/domain/club/entity/QClub.java
src/main/generated/com/back/catchmate/domain/enroll/entity/QEnroll.java
src/main/generated/com/back/catchmate/domain/game/entity/QGame.java
src/main/generated/com/back/catchmate/domain/inquiry/entity/QInquiry.java
src/main/generated/com/back/catchmate/domain/notice/entity/QNotice.java
src/main/generated/com/back/catchmate/domain/notification/entity/QNotification.java
src/main/generated/com/back/catchmate/domain/report/entity/QReport.java
src/main/generated/com/back/catchmate/domain/user/entity/QBlockedUser.java
src/main/generated/com/back/catchmate/domain/user/entity/QUser.java
src/main/generated/com/back/catchmate/global/entity/QBaseTimeEntity.java
src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
src/main/java/com/back/catchmate/domain/enroll/controller/EnrollController.java
src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
src/main/java/com/back/catchmate/domain/enroll/entity/AcceptStatus.java
src/main/java/com/back/catchmate/domain/user/controller/UserController.java
src/main/java/com/back/catchmate/domain/user/repository/BlockedUserRepository.java
src/main/java/com/back/catchmate/domain/user/repository/UserRepository.java
src/main/java/com/back/catchmate/global/auth/entity/RefreshToken.java
src/test/java/com/back/catchmate/domain/enroll/converter/EnrollConverterTest.java

[REFACTOR] 게시글 도메인 관련 코드 리팩토링

---

src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
src/main/java/com/back/catchmate/domain/notification/repository/NotificationRepository.java

#207 
직관신청 수락 & 거절시 발생하는 오류 수정

[FIX] 직관신청 수락 & 거절시 발생하는 오류 수정
