- src/main/java/com/back/catchmate/domain/user/service/UserServiceImpl.java
- src/main/java/com/back/catchmate/global/auth/service/AuthServiceImpl.java
> [FIX] 트랜잭션 어노테이션 추가

- src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
- src/main/java/com/back/catchmate/domain/board/entity/Board.java
- src/main/java/com/back/catchmate/domain/enroll/controller/EnrollController.java
- src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
- src/main/java/com/back/catchmate/domain/enroll/dto/EnrollRequest.java
- src/main/java/com/back/catchmate/domain/enroll/dto/EnrollResponse.java
- src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollService.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
- src/main/java/com/back/catchmate/domain/user/converter/UserConverter.java
- src/main/java/com/back/catchmate/domain/user/service/UserServiceImpl.java
- src/main/java/com/back/catchmate/global/error/ErrorCode.java
> [FEAT] 직관 신청 조회 기능 구현

- src/main/java/com/back/catchmate/domain/enroll/controller/EnrollController.java
- src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
- src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollService.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
- src/main/java/com/back/catchmate/domain/user/entity/User.java
> [FEAT] 직관 신청 수락, 거절 기능 구현

- .github/workflows/deploy.yml
- .gitignore
- build.gradle
- src/main/java/com/back/catchmate/domain/enroll/controller/EnrollController.java
- src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollService.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
- src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java
- src/main/java/com/back/catchmate/domain/notification/dto/FCMMessageRequest.java
- src/main/java/com/back/catchmate/domain/notification/dto/NotificationResponse.java
- src/main/java/com/back/catchmate/domain/notification/entity/Notification.java
- src/main/java/com/back/catchmate/domain/notification/message/NotificationMessages.java
- src/main/java/com/back/catchmate/domain/notification/repository/NotificationRepository.java
- src/main/java/com/back/catchmate/domain/notification/service/FCMService.java
> [FEAT] PUSH 알림 기능 구현

- src/main/java/com/back/catchmate/domain/enroll/controller/EnrollController.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollService.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
- src/main/java/com/back/catchmate/domain/notification/controller/NotificationController.java
- src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java
- src/main/java/com/back/catchmate/domain/notification/dto/NotificationResponse.java
- src/main/java/com/back/catchmate/domain/notification/entity/Notification.java
- src/main/java/com/back/catchmate/domain/notification/message/NotificationMessages.java
- src/main/java/com/back/catchmate/domain/notification/repository/NotificationRepository.java
- src/main/java/com/back/catchmate/domain/notification/service/NotificationService.java
- src/main/java/com/back/catchmate/domain/notification/service/NotificationServiceImpl.java
- src/main/java/com/back/catchmate/domain/user/service/UserServiceImpl.java
> [FEAT] 알림 생성, 조회 기능 구현

- src/main/java/com/back/catchmate/domain/enroll/controller/EnrollController.java
- src/main/java/com/back/catchmate/domain/notification/controller/NotificationController.java
- src/main/java/com/back/catchmate/domain/notification/service/NotificationService.java
- src/main/java/com/back/catchmate/domain/notification/service/NotificationServiceImpl.java
> [FEAT] 알림 삭제 기능 구현

- src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
- src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
- src/main/java/com/back/catchmate/domain/board/converter/BookMarkConverter.java
- src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
- src/main/java/com/back/catchmate/domain/board/entity/Board.java
- src/main/java/com/back/catchmate/domain/board/entity/BookMark.java
- src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
- src/main/java/com/back/catchmate/domain/board/service/BoardService.java
- src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
- src/main/java/com/back/catchmate/domain/board/service/BookMarkService.java
- src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
- src/main/java/com/back/catchmate/domain/game/entity/Game.java
- src/main/java/com/back/catchmate/domain/user/entity/User.java
- src/main/java/com/back/catchmate/global/entity/BaseTimeEntity.java
- src/main/java/com/back/catchmate/global/error/ErrorCode.java
> [FEAT] 게시글 찜 생성, 삭제 기능 구현

- src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
- src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
- src/main/java/com/back/catchmate/domain/board/entity/Board.java
- src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
- src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
- src/main/java/com/back/catchmate/domain/board/service/BoardService.java
- src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
- src/main/java/com/back/catchmate/domain/board/service/BookMarkService.java
- src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
- src/main/java/com/back/catchmate/global/error/ErrorCode.java
> [FEAT] 내가 찜한 게시글 조회 기능 구현

- src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
- src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
- src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
- src/main/java/com/back/catchmate/domain/board/entity/Board.java
- src/main/java/com/back/catchmate/domain/board/service/BoardService.java
- src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
> [FEAT]  게시글 수정 API 리팩토링

- src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
- src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
- src/main/java/com/back/catchmate/domain/board/service/BoardService.java
- src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
- src/main/java/com/back/catchmate/global/error/ErrorCode.java
> [FEAT] 임시저장된 게시글 단일 조회 기능 구현

- src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
- src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
- src/main/java/com/back/catchmate/domain/board/entity/Board.java
> [FIX] 게시글 응답값 수정

- src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
- src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
- src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
- src/main/java/com/back/catchmate/domain/board/entity/Board.java
- src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
- src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/back/catchmate/domain/board/service/BoardService.java
- src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
- src/main/java/com/back/catchmate/global/error/ErrorCode.java
> [FEAT] 게시글 끌어올리기 API 기능 구현

- src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
- src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
- src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
> [FIX] 게시글 작성, 찜하기 오류 수정

- src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
- src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
> [FIX] 게시글 찜 삭제 오류 수정

- src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
- src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
- src/main/java/com/back/catchmate/domain/board/entity/Board.java
- src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
- src/main/java/com/back/catchmate/domain/board/service/BoardService.java
- src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
> [FIX] 임시 저장 게시글 조회 기능 수정

- src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
- src/main/java/com/back/catchmate/domain/chat/dto/ChatRequest.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
- src/main/java/com/back/catchmate/global/config/SecurityConfig.java
> [FIX] 채팅 요청 주소 변경

- src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
- src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
> [FIX] 찜하기 조회 API 오류 수정

- build.gradle
- src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
- src/main/java/com/back/catchmate/domain/chat/converter/ChatMessageConverter.java
- src/main/java/com/back/catchmate/domain/chat/repository/ChatMessageRepository.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
- src/main/java/com/back/catchmate/global/config/MongodbConfig.java
> [FIX] 채팅 내역 API 페이징 오류 수정

- src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
- src/main/java/com/back/catchmate/domain/enroll/dto/EnrollResponse.java
- src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java
> [FIX] 내가 받은 직관 신청 조회 API 수정

- src/main/java/com/back/catchmate/domain/enroll/controller/EnrollController.java
- src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
- src/main/java/com/back/catchmate/domain/enroll/dto/EnrollResponse.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollService.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
> [FEAT] 직관신청 상세조회 API 구현

- src/main/java/com/back/catchmate/domain/enroll/controller/EnrollController.java
- src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
- src/main/java/com/back/catchmate/domain/enroll/dto/EnrollResponse.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
> [FIX] 직관신청 상세 조회 API 수정

- src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
- src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
- src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
- src/main/java/com/back/catchmate/domain/chat/converter/ChatMessageConverter.java
- src/main/java/com/back/catchmate/domain/chat/dto/ChatRequest.java
- src/main/java/com/back/catchmate/domain/chat/entity/ChatMessage.java
- src/main/java/com/back/catchmate/domain/chat/repository/ChatMessageRepository.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
> [FIX] 게시글, 채팅방 응답값 수정

- src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
- src/main/java/com/back/catchmate/domain/chat/converter/ChatMessageConverter.java
- src/main/java/com/back/catchmate/domain/chat/entity/ChatMessage.java
- src/main/java/com/back/catchmate/domain/chat/repository/ChatMessageRepository.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
> [FEAT] 유저 입퇴장시 메세지 전송 기능 구현

- src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java
- src/main/java/com/back/catchmate/domain/chat/converter/ChatRoomConverter.java
- src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
- src/main/java/com/back/catchmate/domain/chat/entity/ChatRoom.java
- src/main/java/com/back/catchmate/domain/chat/repository/UserChatRoomRepository.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatRoomService.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
- src/main/java/com/back/catchmate/global/error/ErrorCode.java
#108  
채팅방 설정 기능 구현
- 채팅방 이미지 설정
- 유저 내보내기 기능
> [FEAT] 채팅방 설정 기능 구현

- src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
- src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
- src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
- src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
- src/main/java/com/back/catchmate/domain/notification/service/FCMService.java
- src/main/java/com/back/catchmate/global/error/ErrorCode.java
토픽 전송 방식에서 토큰을 사용한 전송 방식으로 리팩토링
> [REFACTOR] 토픽 전송 방식에서 토큰을 사용한 전송 방식으로 리팩토링

- src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
- src/main/java/com/back/catchmate/domain/board/entity/Board.java
- src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
- src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
- src/main/java/com/back/catchmate/domain/report/controller/ReportController.java
- src/main/java/com/back/catchmate/domain/report/converter/ReportConverter.java
- src/main/java/com/back/catchmate/domain/report/dto/ReportRequest.java
- src/main/java/com/back/catchmate/domain/report/entity/Report.java
- src/main/java/com/back/catchmate/domain/report/entity/ReportReason.java
- src/main/java/com/back/catchmate/domain/report/repository/ReportRepository.java
- src/main/java/com/back/catchmate/domain/report/service/ReportService.java
- src/main/java/com/back/catchmate/domain/report/service/ReportServiceImpl.java
> [FEAT] 유저 신고 API 구현
